/**
 *
 *  Cards.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Cards.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::cardgame_db;

const std::string Cards::Cols::_id = "\"id\"";
const std::string Cards::Cols::_card_key = "\"card_key\"";
const std::string Cards::Cols::_name = "\"name\"";
const std::string Cards::Cols::_description = "\"description\"";
const std::string Cards::Cols::_mana_cost = "\"mana_cost\"";
const std::string Cards::Cols::_attack = "\"attack\"";
const std::string Cards::Cols::_health = "\"health\"";
const std::string Cards::Cols::_card_type = "\"card_type\"";
const std::string Cards::Cols::_rarity = "\"rarity\"";
const std::string Cards::Cols::_class_type = "\"class_type\"";
const std::string Cards::Cols::_effect_json = "\"effect_json\"";
const std::string Cards::Cols::_image_url = "\"image_url\"";
const std::string Cards::Cols::_is_collectible = "\"is_collectible\"";
const std::string Cards::Cols::_created_at = "\"created_at\"";
const std::string Cards::primaryKeyName = "id";
const bool Cards::hasPrimaryKey = true;
const std::string Cards::tableName = "\"cards\"";

const std::vector<typename Cards::MetaData> Cards::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"card_key","std::string","character varying",64,0,0,1},
{"name","std::string","character varying",64,0,0,1},
{"description","std::string","text",0,0,0,0},
{"mana_cost","int32_t","integer",4,0,0,1},
{"attack","int32_t","integer",4,0,0,0},
{"health","int32_t","integer",4,0,0,0},
{"card_type","std::string","character varying",32,0,0,1},
{"rarity","std::string","character varying",32,0,0,0},
{"class_type","std::string","character varying",32,0,0,0},
{"effect_json","std::string","jsonb",0,0,0,0},
{"image_url","std::string","text",0,0,0,0},
{"is_collectible","bool","boolean",1,0,0,1},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,1}
};
const std::string &Cards::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Cards::Cards(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["card_key"].isNull())
        {
            cardKey_=std::make_shared<std::string>(r["card_key"].as<std::string>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["description"].isNull())
        {
            description_=std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if(!r["mana_cost"].isNull())
        {
            manaCost_=std::make_shared<int32_t>(r["mana_cost"].as<int32_t>());
        }
        if(!r["attack"].isNull())
        {
            attack_=std::make_shared<int32_t>(r["attack"].as<int32_t>());
        }
        if(!r["health"].isNull())
        {
            health_=std::make_shared<int32_t>(r["health"].as<int32_t>());
        }
        if(!r["card_type"].isNull())
        {
            cardType_=std::make_shared<std::string>(r["card_type"].as<std::string>());
        }
        if(!r["rarity"].isNull())
        {
            rarity_=std::make_shared<std::string>(r["rarity"].as<std::string>());
        }
        if(!r["class_type"].isNull())
        {
            classType_=std::make_shared<std::string>(r["class_type"].as<std::string>());
        }
        if(!r["effect_json"].isNull())
        {
            effectJson_=std::make_shared<std::string>(r["effect_json"].as<std::string>());
        }
        if(!r["image_url"].isNull())
        {
            imageUrl_=std::make_shared<std::string>(r["image_url"].as<std::string>());
        }
        if(!r["is_collectible"].isNull())
        {
            isCollectible_=std::make_shared<bool>(r["is_collectible"].as<bool>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 14 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            cardKey_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            description_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            manaCost_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            attack_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            health_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            cardType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            rarity_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            classType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            effectJson_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            imageUrl_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            isCollectible_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Cards::Cards(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            cardKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            manaCost_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            attack_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            health_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            cardType_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            rarity_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            classType_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            effectJson_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            imageUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            isCollectible_=std::make_shared<bool>(pJson[pMasqueradingVector[12]].asBool());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Cards::Cards(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("card_key"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["card_key"].isNull())
        {
            cardKey_=std::make_shared<std::string>(pJson["card_key"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("mana_cost"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["mana_cost"].isNull())
        {
            manaCost_=std::make_shared<int32_t>((int32_t)pJson["mana_cost"].asInt64());
        }
    }
    if(pJson.isMember("attack"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["attack"].isNull())
        {
            attack_=std::make_shared<int32_t>((int32_t)pJson["attack"].asInt64());
        }
    }
    if(pJson.isMember("health"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["health"].isNull())
        {
            health_=std::make_shared<int32_t>((int32_t)pJson["health"].asInt64());
        }
    }
    if(pJson.isMember("card_type"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["card_type"].isNull())
        {
            cardType_=std::make_shared<std::string>(pJson["card_type"].asString());
        }
    }
    if(pJson.isMember("rarity"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["rarity"].isNull())
        {
            rarity_=std::make_shared<std::string>(pJson["rarity"].asString());
        }
    }
    if(pJson.isMember("class_type"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["class_type"].isNull())
        {
            classType_=std::make_shared<std::string>(pJson["class_type"].asString());
        }
    }
    if(pJson.isMember("effect_json"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["effect_json"].isNull())
        {
            effectJson_=std::make_shared<std::string>(pJson["effect_json"].asString());
        }
    }
    if(pJson.isMember("image_url"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["image_url"].isNull())
        {
            imageUrl_=std::make_shared<std::string>(pJson["image_url"].asString());
        }
    }
    if(pJson.isMember("is_collectible"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["is_collectible"].isNull())
        {
            isCollectible_=std::make_shared<bool>(pJson["is_collectible"].asBool());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Cards::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            cardKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            manaCost_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            attack_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            health_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            cardType_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            rarity_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            classType_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            effectJson_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            imageUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            isCollectible_=std::make_shared<bool>(pJson[pMasqueradingVector[12]].asBool());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Cards::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("card_key"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["card_key"].isNull())
        {
            cardKey_=std::make_shared<std::string>(pJson["card_key"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("mana_cost"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["mana_cost"].isNull())
        {
            manaCost_=std::make_shared<int32_t>((int32_t)pJson["mana_cost"].asInt64());
        }
    }
    if(pJson.isMember("attack"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["attack"].isNull())
        {
            attack_=std::make_shared<int32_t>((int32_t)pJson["attack"].asInt64());
        }
    }
    if(pJson.isMember("health"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["health"].isNull())
        {
            health_=std::make_shared<int32_t>((int32_t)pJson["health"].asInt64());
        }
    }
    if(pJson.isMember("card_type"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["card_type"].isNull())
        {
            cardType_=std::make_shared<std::string>(pJson["card_type"].asString());
        }
    }
    if(pJson.isMember("rarity"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["rarity"].isNull())
        {
            rarity_=std::make_shared<std::string>(pJson["rarity"].asString());
        }
    }
    if(pJson.isMember("class_type"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["class_type"].isNull())
        {
            classType_=std::make_shared<std::string>(pJson["class_type"].asString());
        }
    }
    if(pJson.isMember("effect_json"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["effect_json"].isNull())
        {
            effectJson_=std::make_shared<std::string>(pJson["effect_json"].asString());
        }
    }
    if(pJson.isMember("image_url"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["image_url"].isNull())
        {
            imageUrl_=std::make_shared<std::string>(pJson["image_url"].asString());
        }
    }
    if(pJson.isMember("is_collectible"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["is_collectible"].isNull())
        {
            isCollectible_=std::make_shared<bool>(pJson["is_collectible"].asBool());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &Cards::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Cards::getId() const noexcept
{
    return id_;
}
void Cards::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Cards::PrimaryKeyType & Cards::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Cards::getValueOfCardKey() const noexcept
{
    static const std::string defaultValue = std::string();
    if(cardKey_)
        return *cardKey_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Cards::getCardKey() const noexcept
{
    return cardKey_;
}
void Cards::setCardKey(const std::string &pCardKey) noexcept
{
    cardKey_ = std::make_shared<std::string>(pCardKey);
    dirtyFlag_[1] = true;
}
void Cards::setCardKey(std::string &&pCardKey) noexcept
{
    cardKey_ = std::make_shared<std::string>(std::move(pCardKey));
    dirtyFlag_[1] = true;
}

const std::string &Cards::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Cards::getName() const noexcept
{
    return name_;
}
void Cards::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[2] = true;
}
void Cards::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[2] = true;
}

const std::string &Cards::getValueOfDescription() const noexcept
{
    static const std::string defaultValue = std::string();
    if(description_)
        return *description_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Cards::getDescription() const noexcept
{
    return description_;
}
void Cards::setDescription(const std::string &pDescription) noexcept
{
    description_ = std::make_shared<std::string>(pDescription);
    dirtyFlag_[3] = true;
}
void Cards::setDescription(std::string &&pDescription) noexcept
{
    description_ = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[3] = true;
}
void Cards::setDescriptionToNull() noexcept
{
    description_.reset();
    dirtyFlag_[3] = true;
}

const int32_t &Cards::getValueOfManaCost() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(manaCost_)
        return *manaCost_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Cards::getManaCost() const noexcept
{
    return manaCost_;
}
void Cards::setManaCost(const int32_t &pManaCost) noexcept
{
    manaCost_ = std::make_shared<int32_t>(pManaCost);
    dirtyFlag_[4] = true;
}

const int32_t &Cards::getValueOfAttack() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(attack_)
        return *attack_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Cards::getAttack() const noexcept
{
    return attack_;
}
void Cards::setAttack(const int32_t &pAttack) noexcept
{
    attack_ = std::make_shared<int32_t>(pAttack);
    dirtyFlag_[5] = true;
}
void Cards::setAttackToNull() noexcept
{
    attack_.reset();
    dirtyFlag_[5] = true;
}

const int32_t &Cards::getValueOfHealth() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(health_)
        return *health_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Cards::getHealth() const noexcept
{
    return health_;
}
void Cards::setHealth(const int32_t &pHealth) noexcept
{
    health_ = std::make_shared<int32_t>(pHealth);
    dirtyFlag_[6] = true;
}
void Cards::setHealthToNull() noexcept
{
    health_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Cards::getValueOfCardType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(cardType_)
        return *cardType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Cards::getCardType() const noexcept
{
    return cardType_;
}
void Cards::setCardType(const std::string &pCardType) noexcept
{
    cardType_ = std::make_shared<std::string>(pCardType);
    dirtyFlag_[7] = true;
}
void Cards::setCardType(std::string &&pCardType) noexcept
{
    cardType_ = std::make_shared<std::string>(std::move(pCardType));
    dirtyFlag_[7] = true;
}

const std::string &Cards::getValueOfRarity() const noexcept
{
    static const std::string defaultValue = std::string();
    if(rarity_)
        return *rarity_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Cards::getRarity() const noexcept
{
    return rarity_;
}
void Cards::setRarity(const std::string &pRarity) noexcept
{
    rarity_ = std::make_shared<std::string>(pRarity);
    dirtyFlag_[8] = true;
}
void Cards::setRarity(std::string &&pRarity) noexcept
{
    rarity_ = std::make_shared<std::string>(std::move(pRarity));
    dirtyFlag_[8] = true;
}
void Cards::setRarityToNull() noexcept
{
    rarity_.reset();
    dirtyFlag_[8] = true;
}

const std::string &Cards::getValueOfClassType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(classType_)
        return *classType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Cards::getClassType() const noexcept
{
    return classType_;
}
void Cards::setClassType(const std::string &pClassType) noexcept
{
    classType_ = std::make_shared<std::string>(pClassType);
    dirtyFlag_[9] = true;
}
void Cards::setClassType(std::string &&pClassType) noexcept
{
    classType_ = std::make_shared<std::string>(std::move(pClassType));
    dirtyFlag_[9] = true;
}
void Cards::setClassTypeToNull() noexcept
{
    classType_.reset();
    dirtyFlag_[9] = true;
}

const std::string &Cards::getValueOfEffectJson() const noexcept
{
    static const std::string defaultValue = std::string();
    if(effectJson_)
        return *effectJson_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Cards::getEffectJson() const noexcept
{
    return effectJson_;
}
void Cards::setEffectJson(const std::string &pEffectJson) noexcept
{
    effectJson_ = std::make_shared<std::string>(pEffectJson);
    dirtyFlag_[10] = true;
}
void Cards::setEffectJson(std::string &&pEffectJson) noexcept
{
    effectJson_ = std::make_shared<std::string>(std::move(pEffectJson));
    dirtyFlag_[10] = true;
}
void Cards::setEffectJsonToNull() noexcept
{
    effectJson_.reset();
    dirtyFlag_[10] = true;
}

const std::string &Cards::getValueOfImageUrl() const noexcept
{
    static const std::string defaultValue = std::string();
    if(imageUrl_)
        return *imageUrl_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Cards::getImageUrl() const noexcept
{
    return imageUrl_;
}
void Cards::setImageUrl(const std::string &pImageUrl) noexcept
{
    imageUrl_ = std::make_shared<std::string>(pImageUrl);
    dirtyFlag_[11] = true;
}
void Cards::setImageUrl(std::string &&pImageUrl) noexcept
{
    imageUrl_ = std::make_shared<std::string>(std::move(pImageUrl));
    dirtyFlag_[11] = true;
}
void Cards::setImageUrlToNull() noexcept
{
    imageUrl_.reset();
    dirtyFlag_[11] = true;
}

const bool &Cards::getValueOfIsCollectible() const noexcept
{
    static const bool defaultValue = bool();
    if(isCollectible_)
        return *isCollectible_;
    return defaultValue;
}
const std::shared_ptr<bool> &Cards::getIsCollectible() const noexcept
{
    return isCollectible_;
}
void Cards::setIsCollectible(const bool &pIsCollectible) noexcept
{
    isCollectible_ = std::make_shared<bool>(pIsCollectible);
    dirtyFlag_[12] = true;
}

const ::trantor::Date &Cards::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Cards::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Cards::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[13] = true;
}

void Cards::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Cards::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "card_key",
        "name",
        "description",
        "mana_cost",
        "attack",
        "health",
        "card_type",
        "rarity",
        "class_type",
        "effect_json",
        "image_url",
        "is_collectible",
        "created_at"
    };
    return inCols;
}

void Cards::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getCardKey())
        {
            binder << getValueOfCardKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getManaCost())
        {
            binder << getValueOfManaCost();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAttack())
        {
            binder << getValueOfAttack();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getHealth())
        {
            binder << getValueOfHealth();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCardType())
        {
            binder << getValueOfCardType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRarity())
        {
            binder << getValueOfRarity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getClassType())
        {
            binder << getValueOfClassType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getEffectJson())
        {
            binder << getValueOfEffectJson();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getImageUrl())
        {
            binder << getValueOfImageUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getIsCollectible())
        {
            binder << getValueOfIsCollectible();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Cards::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    return ret;
}

void Cards::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getCardKey())
        {
            binder << getValueOfCardKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getManaCost())
        {
            binder << getValueOfManaCost();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAttack())
        {
            binder << getValueOfAttack();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getHealth())
        {
            binder << getValueOfHealth();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCardType())
        {
            binder << getValueOfCardType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRarity())
        {
            binder << getValueOfRarity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getClassType())
        {
            binder << getValueOfClassType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getEffectJson())
        {
            binder << getValueOfEffectJson();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getImageUrl())
        {
            binder << getValueOfImageUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getIsCollectible())
        {
            binder << getValueOfIsCollectible();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Cards::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getCardKey())
    {
        ret["card_key"]=getValueOfCardKey();
    }
    else
    {
        ret["card_key"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getManaCost())
    {
        ret["mana_cost"]=getValueOfManaCost();
    }
    else
    {
        ret["mana_cost"]=Json::Value();
    }
    if(getAttack())
    {
        ret["attack"]=getValueOfAttack();
    }
    else
    {
        ret["attack"]=Json::Value();
    }
    if(getHealth())
    {
        ret["health"]=getValueOfHealth();
    }
    else
    {
        ret["health"]=Json::Value();
    }
    if(getCardType())
    {
        ret["card_type"]=getValueOfCardType();
    }
    else
    {
        ret["card_type"]=Json::Value();
    }
    if(getRarity())
    {
        ret["rarity"]=getValueOfRarity();
    }
    else
    {
        ret["rarity"]=Json::Value();
    }
    if(getClassType())
    {
        ret["class_type"]=getValueOfClassType();
    }
    else
    {
        ret["class_type"]=Json::Value();
    }
    if(getEffectJson())
    {
        ret["effect_json"]=getValueOfEffectJson();
    }
    else
    {
        ret["effect_json"]=Json::Value();
    }
    if(getImageUrl())
    {
        ret["image_url"]=getValueOfImageUrl();
    }
    else
    {
        ret["image_url"]=Json::Value();
    }
    if(getIsCollectible())
    {
        ret["is_collectible"]=getValueOfIsCollectible();
    }
    else
    {
        ret["is_collectible"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string Cards::toString() const
{
    return toJson().toStyledString();
}

Json::Value Cards::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 14)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getCardKey())
            {
                ret[pMasqueradingVector[1]]=getValueOfCardKey();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[2]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDescription())
            {
                ret[pMasqueradingVector[3]]=getValueOfDescription();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getManaCost())
            {
                ret[pMasqueradingVector[4]]=getValueOfManaCost();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getAttack())
            {
                ret[pMasqueradingVector[5]]=getValueOfAttack();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getHealth())
            {
                ret[pMasqueradingVector[6]]=getValueOfHealth();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCardType())
            {
                ret[pMasqueradingVector[7]]=getValueOfCardType();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getRarity())
            {
                ret[pMasqueradingVector[8]]=getValueOfRarity();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getClassType())
            {
                ret[pMasqueradingVector[9]]=getValueOfClassType();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getEffectJson())
            {
                ret[pMasqueradingVector[10]]=getValueOfEffectJson();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getImageUrl())
            {
                ret[pMasqueradingVector[11]]=getValueOfImageUrl();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getIsCollectible())
            {
                ret[pMasqueradingVector[12]]=getValueOfIsCollectible();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[13]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getCardKey())
    {
        ret["card_key"]=getValueOfCardKey();
    }
    else
    {
        ret["card_key"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getManaCost())
    {
        ret["mana_cost"]=getValueOfManaCost();
    }
    else
    {
        ret["mana_cost"]=Json::Value();
    }
    if(getAttack())
    {
        ret["attack"]=getValueOfAttack();
    }
    else
    {
        ret["attack"]=Json::Value();
    }
    if(getHealth())
    {
        ret["health"]=getValueOfHealth();
    }
    else
    {
        ret["health"]=Json::Value();
    }
    if(getCardType())
    {
        ret["card_type"]=getValueOfCardType();
    }
    else
    {
        ret["card_type"]=Json::Value();
    }
    if(getRarity())
    {
        ret["rarity"]=getValueOfRarity();
    }
    else
    {
        ret["rarity"]=Json::Value();
    }
    if(getClassType())
    {
        ret["class_type"]=getValueOfClassType();
    }
    else
    {
        ret["class_type"]=Json::Value();
    }
    if(getEffectJson())
    {
        ret["effect_json"]=getValueOfEffectJson();
    }
    else
    {
        ret["effect_json"]=Json::Value();
    }
    if(getImageUrl())
    {
        ret["image_url"]=getValueOfImageUrl();
    }
    else
    {
        ret["image_url"]=Json::Value();
    }
    if(getIsCollectible())
    {
        ret["is_collectible"]=getValueOfIsCollectible();
    }
    else
    {
        ret["is_collectible"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool Cards::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("card_key"))
    {
        if(!validJsonOfField(1, "card_key", pJson["card_key"], err, true))
            return false;
    }
    else
    {
        err="The card_key column cannot be null";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(2, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(3, "description", pJson["description"], err, true))
            return false;
    }
    if(pJson.isMember("mana_cost"))
    {
        if(!validJsonOfField(4, "mana_cost", pJson["mana_cost"], err, true))
            return false;
    }
    if(pJson.isMember("attack"))
    {
        if(!validJsonOfField(5, "attack", pJson["attack"], err, true))
            return false;
    }
    if(pJson.isMember("health"))
    {
        if(!validJsonOfField(6, "health", pJson["health"], err, true))
            return false;
    }
    if(pJson.isMember("card_type"))
    {
        if(!validJsonOfField(7, "card_type", pJson["card_type"], err, true))
            return false;
    }
    else
    {
        err="The card_type column cannot be null";
        return false;
    }
    if(pJson.isMember("rarity"))
    {
        if(!validJsonOfField(8, "rarity", pJson["rarity"], err, true))
            return false;
    }
    if(pJson.isMember("class_type"))
    {
        if(!validJsonOfField(9, "class_type", pJson["class_type"], err, true))
            return false;
    }
    if(pJson.isMember("effect_json"))
    {
        if(!validJsonOfField(10, "effect_json", pJson["effect_json"], err, true))
            return false;
    }
    if(pJson.isMember("image_url"))
    {
        if(!validJsonOfField(11, "image_url", pJson["image_url"], err, true))
            return false;
    }
    if(pJson.isMember("is_collectible"))
    {
        if(!validJsonOfField(12, "is_collectible", pJson["is_collectible"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(13, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool Cards::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Cards::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("card_key"))
    {
        if(!validJsonOfField(1, "card_key", pJson["card_key"], err, false))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(2, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(3, "description", pJson["description"], err, false))
            return false;
    }
    if(pJson.isMember("mana_cost"))
    {
        if(!validJsonOfField(4, "mana_cost", pJson["mana_cost"], err, false))
            return false;
    }
    if(pJson.isMember("attack"))
    {
        if(!validJsonOfField(5, "attack", pJson["attack"], err, false))
            return false;
    }
    if(pJson.isMember("health"))
    {
        if(!validJsonOfField(6, "health", pJson["health"], err, false))
            return false;
    }
    if(pJson.isMember("card_type"))
    {
        if(!validJsonOfField(7, "card_type", pJson["card_type"], err, false))
            return false;
    }
    if(pJson.isMember("rarity"))
    {
        if(!validJsonOfField(8, "rarity", pJson["rarity"], err, false))
            return false;
    }
    if(pJson.isMember("class_type"))
    {
        if(!validJsonOfField(9, "class_type", pJson["class_type"], err, false))
            return false;
    }
    if(pJson.isMember("effect_json"))
    {
        if(!validJsonOfField(10, "effect_json", pJson["effect_json"], err, false))
            return false;
    }
    if(pJson.isMember("image_url"))
    {
        if(!validJsonOfField(11, "image_url", pJson["image_url"], err, false))
            return false;
    }
    if(pJson.isMember("is_collectible"))
    {
        if(!validJsonOfField(12, "is_collectible", pJson["is_collectible"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(13, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool Cards::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Cards::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
