/**
 *
 *  Cards.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace cardgame_db
{

class Cards
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _card_key;
        static const std::string _name;
        static const std::string _description;
        static const std::string _mana_cost;
        static const std::string _attack;
        static const std::string _health;
        static const std::string _card_type;
        static const std::string _rarity;
        static const std::string _class_type;
        static const std::string _effect_json;
        static const std::string _image_url;
        static const std::string _is_collectible;
        static const std::string _created_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Cards(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Cards(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Cards(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Cards() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column card_key  */
    ///Get the value of the column card_key, returns the default value if the column is null
    const std::string &getValueOfCardKey() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCardKey() const noexcept;
    ///Set the value of the column card_key
    void setCardKey(const std::string &pCardKey) noexcept;
    void setCardKey(std::string &&pCardKey) noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;

    /**  For column description  */
    ///Get the value of the column description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;
    void setDescriptionToNull() noexcept;

    /**  For column mana_cost  */
    ///Get the value of the column mana_cost, returns the default value if the column is null
    const int32_t &getValueOfManaCost() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getManaCost() const noexcept;
    ///Set the value of the column mana_cost
    void setManaCost(const int32_t &pManaCost) noexcept;

    /**  For column attack  */
    ///Get the value of the column attack, returns the default value if the column is null
    const int32_t &getValueOfAttack() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getAttack() const noexcept;
    ///Set the value of the column attack
    void setAttack(const int32_t &pAttack) noexcept;
    void setAttackToNull() noexcept;

    /**  For column health  */
    ///Get the value of the column health, returns the default value if the column is null
    const int32_t &getValueOfHealth() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getHealth() const noexcept;
    ///Set the value of the column health
    void setHealth(const int32_t &pHealth) noexcept;
    void setHealthToNull() noexcept;

    /**  For column card_type  */
    ///Get the value of the column card_type, returns the default value if the column is null
    const std::string &getValueOfCardType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCardType() const noexcept;
    ///Set the value of the column card_type
    void setCardType(const std::string &pCardType) noexcept;
    void setCardType(std::string &&pCardType) noexcept;

    /**  For column rarity  */
    ///Get the value of the column rarity, returns the default value if the column is null
    const std::string &getValueOfRarity() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRarity() const noexcept;
    ///Set the value of the column rarity
    void setRarity(const std::string &pRarity) noexcept;
    void setRarity(std::string &&pRarity) noexcept;
    void setRarityToNull() noexcept;

    /**  For column class_type  */
    ///Get the value of the column class_type, returns the default value if the column is null
    const std::string &getValueOfClassType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClassType() const noexcept;
    ///Set the value of the column class_type
    void setClassType(const std::string &pClassType) noexcept;
    void setClassType(std::string &&pClassType) noexcept;
    void setClassTypeToNull() noexcept;

    /**  For column effect_json  */
    ///Get the value of the column effect_json, returns the default value if the column is null
    const std::string &getValueOfEffectJson() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEffectJson() const noexcept;
    ///Set the value of the column effect_json
    void setEffectJson(const std::string &pEffectJson) noexcept;
    void setEffectJson(std::string &&pEffectJson) noexcept;
    void setEffectJsonToNull() noexcept;

    /**  For column image_url  */
    ///Get the value of the column image_url, returns the default value if the column is null
    const std::string &getValueOfImageUrl() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getImageUrl() const noexcept;
    ///Set the value of the column image_url
    void setImageUrl(const std::string &pImageUrl) noexcept;
    void setImageUrl(std::string &&pImageUrl) noexcept;
    void setImageUrlToNull() noexcept;

    /**  For column is_collectible  */
    ///Get the value of the column is_collectible, returns the default value if the column is null
    const bool &getValueOfIsCollectible() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsCollectible() const noexcept;
    ///Set the value of the column is_collectible
    void setIsCollectible(const bool &pIsCollectible) noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;


    static size_t getColumnNumber() noexcept {  return 14;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Cards>;
    friend drogon::orm::BaseBuilder<Cards, true, true>;
    friend drogon::orm::BaseBuilder<Cards, true, false>;
    friend drogon::orm::BaseBuilder<Cards, false, true>;
    friend drogon::orm::BaseBuilder<Cards, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Cards>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<std::string> cardKey_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<int32_t> manaCost_;
    std::shared_ptr<int32_t> attack_;
    std::shared_ptr<int32_t> health_;
    std::shared_ptr<std::string> cardType_;
    std::shared_ptr<std::string> rarity_;
    std::shared_ptr<std::string> classType_;
    std::shared_ptr<std::string> effectJson_;
    std::shared_ptr<std::string> imageUrl_;
    std::shared_ptr<bool> isCollectible_;
    std::shared_ptr<::trantor::Date> createdAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[14]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "card_key,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "description,";
            ++parametersCount;
        }
        sql += "mana_cost,";
        ++parametersCount;
        if(!dirtyFlag_[4])
        {
            needSelection=true;
        }
        if(dirtyFlag_[5])
        {
            sql += "attack,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "health,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "card_type,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "rarity,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "class_type,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "effect_json,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "image_url,";
            ++parametersCount;
        }
        sql += "is_collectible,";
        ++parametersCount;
        if(!dirtyFlag_[12])
        {
            needSelection=true;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[13])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace cardgame_db
} // namespace drogon_model
