/**
 *
 *  MatchEvents.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MatchEvents.h"
#include "Matches.h"
#include "Users.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::cardgame_db;

const std::string MatchEvents::Cols::_id = "\"id\"";
const std::string MatchEvents::Cols::_match_id = "\"match_id\"";
const std::string MatchEvents::Cols::_turn_number = "\"turn_number\"";
const std::string MatchEvents::Cols::_sequence_number = "\"sequence_number\"";
const std::string MatchEvents::Cols::_user_id = "\"user_id\"";
const std::string MatchEvents::Cols::_event_type = "\"event_type\"";
const std::string MatchEvents::Cols::_event_payload = "\"event_payload\"";
const std::string MatchEvents::Cols::_created_at = "\"created_at\"";
const std::string MatchEvents::primaryKeyName = "id";
const bool MatchEvents::hasPrimaryKey = true;
const std::string MatchEvents::tableName = "\"match_events\"";

const std::vector<typename MatchEvents::MetaData> MatchEvents::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"match_id","int64_t","bigint",8,0,0,1},
{"turn_number","int32_t","integer",4,0,0,1},
{"sequence_number","int32_t","integer",4,0,0,1},
{"user_id","int64_t","bigint",8,0,0,0},
{"event_type","std::string","character varying",64,0,0,1},
{"event_payload","std::string","jsonb",0,0,0,1},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,1}
};
const std::string &MatchEvents::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MatchEvents::MatchEvents(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["match_id"].isNull())
        {
            matchId_=std::make_shared<int64_t>(r["match_id"].as<int64_t>());
        }
        if(!r["turn_number"].isNull())
        {
            turnNumber_=std::make_shared<int32_t>(r["turn_number"].as<int32_t>());
        }
        if(!r["sequence_number"].isNull())
        {
            sequenceNumber_=std::make_shared<int32_t>(r["sequence_number"].as<int32_t>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>(r["user_id"].as<int64_t>());
        }
        if(!r["event_type"].isNull())
        {
            eventType_=std::make_shared<std::string>(r["event_type"].as<std::string>());
        }
        if(!r["event_payload"].isNull())
        {
            eventPayload_=std::make_shared<std::string>(r["event_payload"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            matchId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            turnNumber_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            sequenceNumber_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            eventType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            eventPayload_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

MatchEvents::MatchEvents(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            matchId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            turnNumber_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            sequenceNumber_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            eventType_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            eventPayload_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

MatchEvents::MatchEvents(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("match_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["match_id"].isNull())
        {
            matchId_=std::make_shared<int64_t>((int64_t)pJson["match_id"].asInt64());
        }
    }
    if(pJson.isMember("turn_number"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["turn_number"].isNull())
        {
            turnNumber_=std::make_shared<int32_t>((int32_t)pJson["turn_number"].asInt64());
        }
    }
    if(pJson.isMember("sequence_number"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["sequence_number"].isNull())
        {
            sequenceNumber_=std::make_shared<int32_t>((int32_t)pJson["sequence_number"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("event_type"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["event_type"].isNull())
        {
            eventType_=std::make_shared<std::string>(pJson["event_type"].asString());
        }
    }
    if(pJson.isMember("event_payload"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["event_payload"].isNull())
        {
            eventPayload_=std::make_shared<std::string>(pJson["event_payload"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void MatchEvents::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            matchId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            turnNumber_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            sequenceNumber_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            eventType_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            eventPayload_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void MatchEvents::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("match_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["match_id"].isNull())
        {
            matchId_=std::make_shared<int64_t>((int64_t)pJson["match_id"].asInt64());
        }
    }
    if(pJson.isMember("turn_number"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["turn_number"].isNull())
        {
            turnNumber_=std::make_shared<int32_t>((int32_t)pJson["turn_number"].asInt64());
        }
    }
    if(pJson.isMember("sequence_number"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["sequence_number"].isNull())
        {
            sequenceNumber_=std::make_shared<int32_t>((int32_t)pJson["sequence_number"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("event_type"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["event_type"].isNull())
        {
            eventType_=std::make_shared<std::string>(pJson["event_type"].asString());
        }
    }
    if(pJson.isMember("event_payload"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["event_payload"].isNull())
        {
            eventPayload_=std::make_shared<std::string>(pJson["event_payload"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &MatchEvents::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MatchEvents::getId() const noexcept
{
    return id_;
}
void MatchEvents::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename MatchEvents::PrimaryKeyType & MatchEvents::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &MatchEvents::getValueOfMatchId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(matchId_)
        return *matchId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MatchEvents::getMatchId() const noexcept
{
    return matchId_;
}
void MatchEvents::setMatchId(const int64_t &pMatchId) noexcept
{
    matchId_ = std::make_shared<int64_t>(pMatchId);
    dirtyFlag_[1] = true;
}

const int32_t &MatchEvents::getValueOfTurnNumber() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(turnNumber_)
        return *turnNumber_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &MatchEvents::getTurnNumber() const noexcept
{
    return turnNumber_;
}
void MatchEvents::setTurnNumber(const int32_t &pTurnNumber) noexcept
{
    turnNumber_ = std::make_shared<int32_t>(pTurnNumber);
    dirtyFlag_[2] = true;
}

const int32_t &MatchEvents::getValueOfSequenceNumber() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(sequenceNumber_)
        return *sequenceNumber_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &MatchEvents::getSequenceNumber() const noexcept
{
    return sequenceNumber_;
}
void MatchEvents::setSequenceNumber(const int32_t &pSequenceNumber) noexcept
{
    sequenceNumber_ = std::make_shared<int32_t>(pSequenceNumber);
    dirtyFlag_[3] = true;
}

const int64_t &MatchEvents::getValueOfUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MatchEvents::getUserId() const noexcept
{
    return userId_;
}
void MatchEvents::setUserId(const int64_t &pUserId) noexcept
{
    userId_ = std::make_shared<int64_t>(pUserId);
    dirtyFlag_[4] = true;
}
void MatchEvents::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[4] = true;
}

const std::string &MatchEvents::getValueOfEventType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(eventType_)
        return *eventType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MatchEvents::getEventType() const noexcept
{
    return eventType_;
}
void MatchEvents::setEventType(const std::string &pEventType) noexcept
{
    eventType_ = std::make_shared<std::string>(pEventType);
    dirtyFlag_[5] = true;
}
void MatchEvents::setEventType(std::string &&pEventType) noexcept
{
    eventType_ = std::make_shared<std::string>(std::move(pEventType));
    dirtyFlag_[5] = true;
}

const std::string &MatchEvents::getValueOfEventPayload() const noexcept
{
    static const std::string defaultValue = std::string();
    if(eventPayload_)
        return *eventPayload_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MatchEvents::getEventPayload() const noexcept
{
    return eventPayload_;
}
void MatchEvents::setEventPayload(const std::string &pEventPayload) noexcept
{
    eventPayload_ = std::make_shared<std::string>(pEventPayload);
    dirtyFlag_[6] = true;
}
void MatchEvents::setEventPayload(std::string &&pEventPayload) noexcept
{
    eventPayload_ = std::make_shared<std::string>(std::move(pEventPayload));
    dirtyFlag_[6] = true;
}

const ::trantor::Date &MatchEvents::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MatchEvents::getCreatedAt() const noexcept
{
    return createdAt_;
}
void MatchEvents::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[7] = true;
}

void MatchEvents::updateId(const uint64_t id)
{
}

const std::vector<std::string> &MatchEvents::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "match_id",
        "turn_number",
        "sequence_number",
        "user_id",
        "event_type",
        "event_payload",
        "created_at"
    };
    return inCols;
}

void MatchEvents::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMatchId())
        {
            binder << getValueOfMatchId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTurnNumber())
        {
            binder << getValueOfTurnNumber();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSequenceNumber())
        {
            binder << getValueOfSequenceNumber();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEventType())
        {
            binder << getValueOfEventType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getEventPayload())
        {
            binder << getValueOfEventPayload();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MatchEvents::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void MatchEvents::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMatchId())
        {
            binder << getValueOfMatchId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTurnNumber())
        {
            binder << getValueOfTurnNumber();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSequenceNumber())
        {
            binder << getValueOfSequenceNumber();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEventType())
        {
            binder << getValueOfEventType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getEventPayload())
        {
            binder << getValueOfEventPayload();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MatchEvents::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMatchId())
    {
        ret["match_id"]=(Json::Int64)getValueOfMatchId();
    }
    else
    {
        ret["match_id"]=Json::Value();
    }
    if(getTurnNumber())
    {
        ret["turn_number"]=getValueOfTurnNumber();
    }
    else
    {
        ret["turn_number"]=Json::Value();
    }
    if(getSequenceNumber())
    {
        ret["sequence_number"]=getValueOfSequenceNumber();
    }
    else
    {
        ret["sequence_number"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getEventType())
    {
        ret["event_type"]=getValueOfEventType();
    }
    else
    {
        ret["event_type"]=Json::Value();
    }
    if(getEventPayload())
    {
        ret["event_payload"]=getValueOfEventPayload();
    }
    else
    {
        ret["event_payload"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string MatchEvents::toString() const
{
    return toJson().toStyledString();
}

Json::Value MatchEvents::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMatchId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfMatchId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTurnNumber())
            {
                ret[pMasqueradingVector[2]]=getValueOfTurnNumber();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSequenceNumber())
            {
                ret[pMasqueradingVector[3]]=getValueOfSequenceNumber();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[4]]=(Json::Int64)getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getEventType())
            {
                ret[pMasqueradingVector[5]]=getValueOfEventType();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getEventPayload())
            {
                ret[pMasqueradingVector[6]]=getValueOfEventPayload();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[7]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMatchId())
    {
        ret["match_id"]=(Json::Int64)getValueOfMatchId();
    }
    else
    {
        ret["match_id"]=Json::Value();
    }
    if(getTurnNumber())
    {
        ret["turn_number"]=getValueOfTurnNumber();
    }
    else
    {
        ret["turn_number"]=Json::Value();
    }
    if(getSequenceNumber())
    {
        ret["sequence_number"]=getValueOfSequenceNumber();
    }
    else
    {
        ret["sequence_number"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getEventType())
    {
        ret["event_type"]=getValueOfEventType();
    }
    else
    {
        ret["event_type"]=Json::Value();
    }
    if(getEventPayload())
    {
        ret["event_payload"]=getValueOfEventPayload();
    }
    else
    {
        ret["event_payload"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool MatchEvents::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("match_id"))
    {
        if(!validJsonOfField(1, "match_id", pJson["match_id"], err, true))
            return false;
    }
    else
    {
        err="The match_id column cannot be null";
        return false;
    }
    if(pJson.isMember("turn_number"))
    {
        if(!validJsonOfField(2, "turn_number", pJson["turn_number"], err, true))
            return false;
    }
    if(pJson.isMember("sequence_number"))
    {
        if(!validJsonOfField(3, "sequence_number", pJson["sequence_number"], err, true))
            return false;
    }
    else
    {
        err="The sequence_number column cannot be null";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(4, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("event_type"))
    {
        if(!validJsonOfField(5, "event_type", pJson["event_type"], err, true))
            return false;
    }
    else
    {
        err="The event_type column cannot be null";
        return false;
    }
    if(pJson.isMember("event_payload"))
    {
        if(!validJsonOfField(6, "event_payload", pJson["event_payload"], err, true))
            return false;
    }
    else
    {
        err="The event_payload column cannot be null";
        return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool MatchEvents::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MatchEvents::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("match_id"))
    {
        if(!validJsonOfField(1, "match_id", pJson["match_id"], err, false))
            return false;
    }
    if(pJson.isMember("turn_number"))
    {
        if(!validJsonOfField(2, "turn_number", pJson["turn_number"], err, false))
            return false;
    }
    if(pJson.isMember("sequence_number"))
    {
        if(!validJsonOfField(3, "sequence_number", pJson["sequence_number"], err, false))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(4, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("event_type"))
    {
        if(!validJsonOfField(5, "event_type", pJson["event_type"], err, false))
            return false;
    }
    if(pJson.isMember("event_payload"))
    {
        if(!validJsonOfField(6, "event_payload", pJson["event_payload"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool MatchEvents::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MatchEvents::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Users MatchEvents::getUsers(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from users where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *userId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Users(r[0]);
}

void MatchEvents::getUsers(const DbClientPtr &clientPtr,
                           const std::function<void(Users)> &rcb,
                           const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from users where id = $1";
    *clientPtr << sql
               << *userId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Users(r[0]));
                    }
               }
               >> ecb;
}
Matches MatchEvents::getMatches(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from matches where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *matchId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Matches(r[0]);
}

void MatchEvents::getMatches(const DbClientPtr &clientPtr,
                             const std::function<void(Matches)> &rcb,
                             const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from matches where id = $1";
    *clientPtr << sql
               << *matchId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Matches(r[0]));
                    }
               }
               >> ecb;
}
