/**
 *
 *  MatchPlayers.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace cardgame_db
{
class Decks;
class Matches;
class Users;

class MatchPlayers
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _match_id;
        static const std::string _user_id;
        static const std::string _deck_id;
        static const std::string _result;
        static const std::string _rating_before;
        static const std::string _rating_after;
        static const std::string _created_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit MatchPlayers(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit MatchPlayers(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    MatchPlayers(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    MatchPlayers() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column match_id  */
    ///Get the value of the column match_id, returns the default value if the column is null
    const int64_t &getValueOfMatchId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getMatchId() const noexcept;
    ///Set the value of the column match_id
    void setMatchId(const int64_t &pMatchId) noexcept;

    /**  For column user_id  */
    ///Get the value of the column user_id, returns the default value if the column is null
    const int64_t &getValueOfUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getUserId() const noexcept;
    ///Set the value of the column user_id
    void setUserId(const int64_t &pUserId) noexcept;

    /**  For column deck_id  */
    ///Get the value of the column deck_id, returns the default value if the column is null
    const int64_t &getValueOfDeckId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getDeckId() const noexcept;
    ///Set the value of the column deck_id
    void setDeckId(const int64_t &pDeckId) noexcept;
    void setDeckIdToNull() noexcept;

    /**  For column result  */
    ///Get the value of the column result, returns the default value if the column is null
    const std::string &getValueOfResult() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getResult() const noexcept;
    ///Set the value of the column result
    void setResult(const std::string &pResult) noexcept;
    void setResult(std::string &&pResult) noexcept;

    /**  For column rating_before  */
    ///Get the value of the column rating_before, returns the default value if the column is null
    const int32_t &getValueOfRatingBefore() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getRatingBefore() const noexcept;
    ///Set the value of the column rating_before
    void setRatingBefore(const int32_t &pRatingBefore) noexcept;
    void setRatingBeforeToNull() noexcept;

    /**  For column rating_after  */
    ///Get the value of the column rating_after, returns the default value if the column is null
    const int32_t &getValueOfRatingAfter() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getRatingAfter() const noexcept;
    ///Set the value of the column rating_after
    void setRatingAfter(const int32_t &pRatingAfter) noexcept;
    void setRatingAfterToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;


    static size_t getColumnNumber() noexcept {  return 8;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    Users getUsers(const drogon::orm::DbClientPtr &clientPtr) const;
    void getUsers(const drogon::orm::DbClientPtr &clientPtr,
                  const std::function<void(Users)> &rcb,
                  const drogon::orm::ExceptionCallback &ecb) const;
    Decks getDecks(const drogon::orm::DbClientPtr &clientPtr) const;
    void getDecks(const drogon::orm::DbClientPtr &clientPtr,
                  const std::function<void(Decks)> &rcb,
                  const drogon::orm::ExceptionCallback &ecb) const;
    Matches getMatches(const drogon::orm::DbClientPtr &clientPtr) const;
    void getMatches(const drogon::orm::DbClientPtr &clientPtr,
                    const std::function<void(Matches)> &rcb,
                    const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<MatchPlayers>;
    friend drogon::orm::BaseBuilder<MatchPlayers, true, true>;
    friend drogon::orm::BaseBuilder<MatchPlayers, true, false>;
    friend drogon::orm::BaseBuilder<MatchPlayers, false, true>;
    friend drogon::orm::BaseBuilder<MatchPlayers, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<MatchPlayers>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<int64_t> matchId_;
    std::shared_ptr<int64_t> userId_;
    std::shared_ptr<int64_t> deckId_;
    std::shared_ptr<std::string> result_;
    std::shared_ptr<int32_t> ratingBefore_;
    std::shared_ptr<int32_t> ratingAfter_;
    std::shared_ptr<::trantor::Date> createdAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "match_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "user_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "deck_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "result,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "rating_before,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "rating_after,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace cardgame_db
} // namespace drogon_model
