/**
 *
 *  MatchPlayers.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MatchPlayers.h"
#include "Decks.h"
#include "Matches.h"
#include "Users.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::cardgame_db;

const std::string MatchPlayers::Cols::_id = "\"id\"";
const std::string MatchPlayers::Cols::_match_id = "\"match_id\"";
const std::string MatchPlayers::Cols::_user_id = "\"user_id\"";
const std::string MatchPlayers::Cols::_deck_id = "\"deck_id\"";
const std::string MatchPlayers::Cols::_result = "\"result\"";
const std::string MatchPlayers::Cols::_rating_before = "\"rating_before\"";
const std::string MatchPlayers::Cols::_rating_after = "\"rating_after\"";
const std::string MatchPlayers::Cols::_created_at = "\"created_at\"";
const std::string MatchPlayers::primaryKeyName = "id";
const bool MatchPlayers::hasPrimaryKey = true;
const std::string MatchPlayers::tableName = "\"match_players\"";

const std::vector<typename MatchPlayers::MetaData> MatchPlayers::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"match_id","int64_t","bigint",8,0,0,1},
{"user_id","int64_t","bigint",8,0,0,1},
{"deck_id","int64_t","bigint",8,0,0,0},
{"result","std::string","character varying",32,0,0,1},
{"rating_before","int32_t","integer",4,0,0,0},
{"rating_after","int32_t","integer",4,0,0,0},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,1}
};
const std::string &MatchPlayers::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MatchPlayers::MatchPlayers(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["match_id"].isNull())
        {
            matchId_=std::make_shared<int64_t>(r["match_id"].as<int64_t>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>(r["user_id"].as<int64_t>());
        }
        if(!r["deck_id"].isNull())
        {
            deckId_=std::make_shared<int64_t>(r["deck_id"].as<int64_t>());
        }
        if(!r["result"].isNull())
        {
            result_=std::make_shared<std::string>(r["result"].as<std::string>());
        }
        if(!r["rating_before"].isNull())
        {
            ratingBefore_=std::make_shared<int32_t>(r["rating_before"].as<int32_t>());
        }
        if(!r["rating_after"].isNull())
        {
            ratingAfter_=std::make_shared<int32_t>(r["rating_after"].as<int32_t>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            matchId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            deckId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            result_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            ratingBefore_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            ratingAfter_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

MatchPlayers::MatchPlayers(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            matchId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            deckId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            result_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            ratingBefore_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            ratingAfter_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

MatchPlayers::MatchPlayers(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("match_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["match_id"].isNull())
        {
            matchId_=std::make_shared<int64_t>((int64_t)pJson["match_id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("deck_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["deck_id"].isNull())
        {
            deckId_=std::make_shared<int64_t>((int64_t)pJson["deck_id"].asInt64());
        }
    }
    if(pJson.isMember("result"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["result"].isNull())
        {
            result_=std::make_shared<std::string>(pJson["result"].asString());
        }
    }
    if(pJson.isMember("rating_before"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["rating_before"].isNull())
        {
            ratingBefore_=std::make_shared<int32_t>((int32_t)pJson["rating_before"].asInt64());
        }
    }
    if(pJson.isMember("rating_after"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["rating_after"].isNull())
        {
            ratingAfter_=std::make_shared<int32_t>((int32_t)pJson["rating_after"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void MatchPlayers::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            matchId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            deckId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            result_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            ratingBefore_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            ratingAfter_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void MatchPlayers::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("match_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["match_id"].isNull())
        {
            matchId_=std::make_shared<int64_t>((int64_t)pJson["match_id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("deck_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["deck_id"].isNull())
        {
            deckId_=std::make_shared<int64_t>((int64_t)pJson["deck_id"].asInt64());
        }
    }
    if(pJson.isMember("result"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["result"].isNull())
        {
            result_=std::make_shared<std::string>(pJson["result"].asString());
        }
    }
    if(pJson.isMember("rating_before"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["rating_before"].isNull())
        {
            ratingBefore_=std::make_shared<int32_t>((int32_t)pJson["rating_before"].asInt64());
        }
    }
    if(pJson.isMember("rating_after"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["rating_after"].isNull())
        {
            ratingAfter_=std::make_shared<int32_t>((int32_t)pJson["rating_after"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &MatchPlayers::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MatchPlayers::getId() const noexcept
{
    return id_;
}
void MatchPlayers::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename MatchPlayers::PrimaryKeyType & MatchPlayers::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &MatchPlayers::getValueOfMatchId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(matchId_)
        return *matchId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MatchPlayers::getMatchId() const noexcept
{
    return matchId_;
}
void MatchPlayers::setMatchId(const int64_t &pMatchId) noexcept
{
    matchId_ = std::make_shared<int64_t>(pMatchId);
    dirtyFlag_[1] = true;
}

const int64_t &MatchPlayers::getValueOfUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MatchPlayers::getUserId() const noexcept
{
    return userId_;
}
void MatchPlayers::setUserId(const int64_t &pUserId) noexcept
{
    userId_ = std::make_shared<int64_t>(pUserId);
    dirtyFlag_[2] = true;
}

const int64_t &MatchPlayers::getValueOfDeckId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(deckId_)
        return *deckId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MatchPlayers::getDeckId() const noexcept
{
    return deckId_;
}
void MatchPlayers::setDeckId(const int64_t &pDeckId) noexcept
{
    deckId_ = std::make_shared<int64_t>(pDeckId);
    dirtyFlag_[3] = true;
}
void MatchPlayers::setDeckIdToNull() noexcept
{
    deckId_.reset();
    dirtyFlag_[3] = true;
}

const std::string &MatchPlayers::getValueOfResult() const noexcept
{
    static const std::string defaultValue = std::string();
    if(result_)
        return *result_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MatchPlayers::getResult() const noexcept
{
    return result_;
}
void MatchPlayers::setResult(const std::string &pResult) noexcept
{
    result_ = std::make_shared<std::string>(pResult);
    dirtyFlag_[4] = true;
}
void MatchPlayers::setResult(std::string &&pResult) noexcept
{
    result_ = std::make_shared<std::string>(std::move(pResult));
    dirtyFlag_[4] = true;
}

const int32_t &MatchPlayers::getValueOfRatingBefore() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(ratingBefore_)
        return *ratingBefore_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &MatchPlayers::getRatingBefore() const noexcept
{
    return ratingBefore_;
}
void MatchPlayers::setRatingBefore(const int32_t &pRatingBefore) noexcept
{
    ratingBefore_ = std::make_shared<int32_t>(pRatingBefore);
    dirtyFlag_[5] = true;
}
void MatchPlayers::setRatingBeforeToNull() noexcept
{
    ratingBefore_.reset();
    dirtyFlag_[5] = true;
}

const int32_t &MatchPlayers::getValueOfRatingAfter() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(ratingAfter_)
        return *ratingAfter_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &MatchPlayers::getRatingAfter() const noexcept
{
    return ratingAfter_;
}
void MatchPlayers::setRatingAfter(const int32_t &pRatingAfter) noexcept
{
    ratingAfter_ = std::make_shared<int32_t>(pRatingAfter);
    dirtyFlag_[6] = true;
}
void MatchPlayers::setRatingAfterToNull() noexcept
{
    ratingAfter_.reset();
    dirtyFlag_[6] = true;
}

const ::trantor::Date &MatchPlayers::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MatchPlayers::getCreatedAt() const noexcept
{
    return createdAt_;
}
void MatchPlayers::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[7] = true;
}

void MatchPlayers::updateId(const uint64_t id)
{
}

const std::vector<std::string> &MatchPlayers::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "match_id",
        "user_id",
        "deck_id",
        "result",
        "rating_before",
        "rating_after",
        "created_at"
    };
    return inCols;
}

void MatchPlayers::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMatchId())
        {
            binder << getValueOfMatchId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDeckId())
        {
            binder << getValueOfDeckId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getResult())
        {
            binder << getValueOfResult();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getRatingBefore())
        {
            binder << getValueOfRatingBefore();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getRatingAfter())
        {
            binder << getValueOfRatingAfter();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MatchPlayers::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void MatchPlayers::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMatchId())
        {
            binder << getValueOfMatchId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDeckId())
        {
            binder << getValueOfDeckId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getResult())
        {
            binder << getValueOfResult();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getRatingBefore())
        {
            binder << getValueOfRatingBefore();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getRatingAfter())
        {
            binder << getValueOfRatingAfter();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MatchPlayers::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMatchId())
    {
        ret["match_id"]=(Json::Int64)getValueOfMatchId();
    }
    else
    {
        ret["match_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getDeckId())
    {
        ret["deck_id"]=(Json::Int64)getValueOfDeckId();
    }
    else
    {
        ret["deck_id"]=Json::Value();
    }
    if(getResult())
    {
        ret["result"]=getValueOfResult();
    }
    else
    {
        ret["result"]=Json::Value();
    }
    if(getRatingBefore())
    {
        ret["rating_before"]=getValueOfRatingBefore();
    }
    else
    {
        ret["rating_before"]=Json::Value();
    }
    if(getRatingAfter())
    {
        ret["rating_after"]=getValueOfRatingAfter();
    }
    else
    {
        ret["rating_after"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string MatchPlayers::toString() const
{
    return toJson().toStyledString();
}

Json::Value MatchPlayers::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMatchId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfMatchId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDeckId())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfDeckId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getResult())
            {
                ret[pMasqueradingVector[4]]=getValueOfResult();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getRatingBefore())
            {
                ret[pMasqueradingVector[5]]=getValueOfRatingBefore();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getRatingAfter())
            {
                ret[pMasqueradingVector[6]]=getValueOfRatingAfter();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[7]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMatchId())
    {
        ret["match_id"]=(Json::Int64)getValueOfMatchId();
    }
    else
    {
        ret["match_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getDeckId())
    {
        ret["deck_id"]=(Json::Int64)getValueOfDeckId();
    }
    else
    {
        ret["deck_id"]=Json::Value();
    }
    if(getResult())
    {
        ret["result"]=getValueOfResult();
    }
    else
    {
        ret["result"]=Json::Value();
    }
    if(getRatingBefore())
    {
        ret["rating_before"]=getValueOfRatingBefore();
    }
    else
    {
        ret["rating_before"]=Json::Value();
    }
    if(getRatingAfter())
    {
        ret["rating_after"]=getValueOfRatingAfter();
    }
    else
    {
        ret["rating_after"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool MatchPlayers::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("match_id"))
    {
        if(!validJsonOfField(1, "match_id", pJson["match_id"], err, true))
            return false;
    }
    else
    {
        err="The match_id column cannot be null";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("deck_id"))
    {
        if(!validJsonOfField(3, "deck_id", pJson["deck_id"], err, true))
            return false;
    }
    if(pJson.isMember("result"))
    {
        if(!validJsonOfField(4, "result", pJson["result"], err, true))
            return false;
    }
    else
    {
        err="The result column cannot be null";
        return false;
    }
    if(pJson.isMember("rating_before"))
    {
        if(!validJsonOfField(5, "rating_before", pJson["rating_before"], err, true))
            return false;
    }
    if(pJson.isMember("rating_after"))
    {
        if(!validJsonOfField(6, "rating_after", pJson["rating_after"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool MatchPlayers::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MatchPlayers::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("match_id"))
    {
        if(!validJsonOfField(1, "match_id", pJson["match_id"], err, false))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("deck_id"))
    {
        if(!validJsonOfField(3, "deck_id", pJson["deck_id"], err, false))
            return false;
    }
    if(pJson.isMember("result"))
    {
        if(!validJsonOfField(4, "result", pJson["result"], err, false))
            return false;
    }
    if(pJson.isMember("rating_before"))
    {
        if(!validJsonOfField(5, "rating_before", pJson["rating_before"], err, false))
            return false;
    }
    if(pJson.isMember("rating_after"))
    {
        if(!validJsonOfField(6, "rating_after", pJson["rating_after"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool MatchPlayers::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MatchPlayers::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Users MatchPlayers::getUsers(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from users where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *userId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Users(r[0]);
}

void MatchPlayers::getUsers(const DbClientPtr &clientPtr,
                            const std::function<void(Users)> &rcb,
                            const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from users where id = $1";
    *clientPtr << sql
               << *userId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Users(r[0]));
                    }
               }
               >> ecb;
}
Decks MatchPlayers::getDecks(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from decks where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *deckId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Decks(r[0]);
}

void MatchPlayers::getDecks(const DbClientPtr &clientPtr,
                            const std::function<void(Decks)> &rcb,
                            const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from decks where id = $1";
    *clientPtr << sql
               << *deckId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Decks(r[0]));
                    }
               }
               >> ecb;
}
Matches MatchPlayers::getMatches(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from matches where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *matchId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Matches(r[0]);
}

void MatchPlayers::getMatches(const DbClientPtr &clientPtr,
                              const std::function<void(Matches)> &rcb,
                              const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from matches where id = $1";
    *clientPtr << sql
               << *matchId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Matches(r[0]));
                    }
               }
               >> ecb;
}
