/**
 *
 *  PlayerStats.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PlayerStats.h"
#include "Users.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::cardgame_db;

const std::string PlayerStats::Cols::_user_id = "\"user_id\"";
const std::string PlayerStats::Cols::_rating = "\"rating\"";
const std::string PlayerStats::Cols::_wins = "\"wins\"";
const std::string PlayerStats::Cols::_losses = "\"losses\"";
const std::string PlayerStats::Cols::_draws = "\"draws\"";
const std::string PlayerStats::Cols::_total_matches = "\"total_matches\"";
const std::string PlayerStats::Cols::_updated_at = "\"updated_at\"";
const std::string PlayerStats::primaryKeyName = "user_id";
const bool PlayerStats::hasPrimaryKey = true;
const std::string PlayerStats::tableName = "\"player_stats\"";

const std::vector<typename PlayerStats::MetaData> PlayerStats::metaData_={
{"user_id","int64_t","bigint",8,0,1,1},
{"rating","int32_t","integer",4,0,0,1},
{"wins","int32_t","integer",4,0,0,1},
{"losses","int32_t","integer",4,0,0,1},
{"draws","int32_t","integer",4,0,0,1},
{"total_matches","int32_t","integer",4,0,0,1},
{"updated_at","::trantor::Date","timestamp without time zone",0,0,0,1}
};
const std::string &PlayerStats::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PlayerStats::PlayerStats(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>(r["user_id"].as<int64_t>());
        }
        if(!r["rating"].isNull())
        {
            rating_=std::make_shared<int32_t>(r["rating"].as<int32_t>());
        }
        if(!r["wins"].isNull())
        {
            wins_=std::make_shared<int32_t>(r["wins"].as<int32_t>());
        }
        if(!r["losses"].isNull())
        {
            losses_=std::make_shared<int32_t>(r["losses"].as<int32_t>());
        }
        if(!r["draws"].isNull())
        {
            draws_=std::make_shared<int32_t>(r["draws"].as<int32_t>());
        }
        if(!r["total_matches"].isNull())
        {
            totalMatches_=std::make_shared<int32_t>(r["total_matches"].as<int32_t>());
        }
        if(!r["updated_at"].isNull())
        {
            auto timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            rating_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            wins_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            losses_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            draws_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            totalMatches_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

PlayerStats::PlayerStats(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            wins_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            losses_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            draws_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            totalMatches_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

PlayerStats::PlayerStats(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("rating"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["rating"].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson["rating"].asInt64());
        }
    }
    if(pJson.isMember("wins"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["wins"].isNull())
        {
            wins_=std::make_shared<int32_t>((int32_t)pJson["wins"].asInt64());
        }
    }
    if(pJson.isMember("losses"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["losses"].isNull())
        {
            losses_=std::make_shared<int32_t>((int32_t)pJson["losses"].asInt64());
        }
    }
    if(pJson.isMember("draws"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["draws"].isNull())
        {
            draws_=std::make_shared<int32_t>((int32_t)pJson["draws"].asInt64());
        }
    }
    if(pJson.isMember("total_matches"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["total_matches"].isNull())
        {
            totalMatches_=std::make_shared<int32_t>((int32_t)pJson["total_matches"].asInt64());
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void PlayerStats::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            wins_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            losses_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            draws_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            totalMatches_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void PlayerStats::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("rating"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["rating"].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson["rating"].asInt64());
        }
    }
    if(pJson.isMember("wins"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["wins"].isNull())
        {
            wins_=std::make_shared<int32_t>((int32_t)pJson["wins"].asInt64());
        }
    }
    if(pJson.isMember("losses"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["losses"].isNull())
        {
            losses_=std::make_shared<int32_t>((int32_t)pJson["losses"].asInt64());
        }
    }
    if(pJson.isMember("draws"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["draws"].isNull())
        {
            draws_=std::make_shared<int32_t>((int32_t)pJson["draws"].asInt64());
        }
    }
    if(pJson.isMember("total_matches"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["total_matches"].isNull())
        {
            totalMatches_=std::make_shared<int32_t>((int32_t)pJson["total_matches"].asInt64());
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &PlayerStats::getValueOfUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PlayerStats::getUserId() const noexcept
{
    return userId_;
}
void PlayerStats::setUserId(const int64_t &pUserId) noexcept
{
    userId_ = std::make_shared<int64_t>(pUserId);
    dirtyFlag_[0] = true;
}
const typename PlayerStats::PrimaryKeyType & PlayerStats::getPrimaryKey() const
{
    assert(userId_);
    return *userId_;
}

const int32_t &PlayerStats::getValueOfRating() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(rating_)
        return *rating_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PlayerStats::getRating() const noexcept
{
    return rating_;
}
void PlayerStats::setRating(const int32_t &pRating) noexcept
{
    rating_ = std::make_shared<int32_t>(pRating);
    dirtyFlag_[1] = true;
}

const int32_t &PlayerStats::getValueOfWins() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(wins_)
        return *wins_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PlayerStats::getWins() const noexcept
{
    return wins_;
}
void PlayerStats::setWins(const int32_t &pWins) noexcept
{
    wins_ = std::make_shared<int32_t>(pWins);
    dirtyFlag_[2] = true;
}

const int32_t &PlayerStats::getValueOfLosses() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(losses_)
        return *losses_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PlayerStats::getLosses() const noexcept
{
    return losses_;
}
void PlayerStats::setLosses(const int32_t &pLosses) noexcept
{
    losses_ = std::make_shared<int32_t>(pLosses);
    dirtyFlag_[3] = true;
}

const int32_t &PlayerStats::getValueOfDraws() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(draws_)
        return *draws_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PlayerStats::getDraws() const noexcept
{
    return draws_;
}
void PlayerStats::setDraws(const int32_t &pDraws) noexcept
{
    draws_ = std::make_shared<int32_t>(pDraws);
    dirtyFlag_[4] = true;
}

const int32_t &PlayerStats::getValueOfTotalMatches() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(totalMatches_)
        return *totalMatches_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PlayerStats::getTotalMatches() const noexcept
{
    return totalMatches_;
}
void PlayerStats::setTotalMatches(const int32_t &pTotalMatches) noexcept
{
    totalMatches_ = std::make_shared<int32_t>(pTotalMatches);
    dirtyFlag_[5] = true;
}

const ::trantor::Date &PlayerStats::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PlayerStats::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void PlayerStats::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept
{
    updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[6] = true;
}

void PlayerStats::updateId(const uint64_t id)
{
}

const std::vector<std::string> &PlayerStats::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "user_id",
        "rating",
        "wins",
        "losses",
        "draws",
        "total_matches",
        "updated_at"
    };
    return inCols;
}

void PlayerStats::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRating())
        {
            binder << getValueOfRating();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getWins())
        {
            binder << getValueOfWins();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLosses())
        {
            binder << getValueOfLosses();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDraws())
        {
            binder << getValueOfDraws();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTotalMatches())
        {
            binder << getValueOfTotalMatches();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PlayerStats::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void PlayerStats::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRating())
        {
            binder << getValueOfRating();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getWins())
        {
            binder << getValueOfWins();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLosses())
        {
            binder << getValueOfLosses();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDraws())
        {
            binder << getValueOfDraws();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTotalMatches())
        {
            binder << getValueOfTotalMatches();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PlayerStats::toJson() const
{
    Json::Value ret;
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getRating())
    {
        ret["rating"]=getValueOfRating();
    }
    else
    {
        ret["rating"]=Json::Value();
    }
    if(getWins())
    {
        ret["wins"]=getValueOfWins();
    }
    else
    {
        ret["wins"]=Json::Value();
    }
    if(getLosses())
    {
        ret["losses"]=getValueOfLosses();
    }
    else
    {
        ret["losses"]=Json::Value();
    }
    if(getDraws())
    {
        ret["draws"]=getValueOfDraws();
    }
    else
    {
        ret["draws"]=Json::Value();
    }
    if(getTotalMatches())
    {
        ret["total_matches"]=getValueOfTotalMatches();
    }
    else
    {
        ret["total_matches"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

std::string PlayerStats::toString() const
{
    return toJson().toStyledString();
}

Json::Value PlayerStats::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getRating())
            {
                ret[pMasqueradingVector[1]]=getValueOfRating();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getWins())
            {
                ret[pMasqueradingVector[2]]=getValueOfWins();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getLosses())
            {
                ret[pMasqueradingVector[3]]=getValueOfLosses();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getDraws())
            {
                ret[pMasqueradingVector[4]]=getValueOfDraws();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getTotalMatches())
            {
                ret[pMasqueradingVector[5]]=getValueOfTotalMatches();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getUpdatedAt())
            {
                ret[pMasqueradingVector[6]]=getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getRating())
    {
        ret["rating"]=getValueOfRating();
    }
    else
    {
        ret["rating"]=Json::Value();
    }
    if(getWins())
    {
        ret["wins"]=getValueOfWins();
    }
    else
    {
        ret["wins"]=Json::Value();
    }
    if(getLosses())
    {
        ret["losses"]=getValueOfLosses();
    }
    else
    {
        ret["losses"]=Json::Value();
    }
    if(getDraws())
    {
        ret["draws"]=getValueOfDraws();
    }
    else
    {
        ret["draws"]=Json::Value();
    }
    if(getTotalMatches())
    {
        ret["total_matches"]=getValueOfTotalMatches();
    }
    else
    {
        ret["total_matches"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

bool PlayerStats::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("rating"))
    {
        if(!validJsonOfField(1, "rating", pJson["rating"], err, true))
            return false;
    }
    if(pJson.isMember("wins"))
    {
        if(!validJsonOfField(2, "wins", pJson["wins"], err, true))
            return false;
    }
    if(pJson.isMember("losses"))
    {
        if(!validJsonOfField(3, "losses", pJson["losses"], err, true))
            return false;
    }
    if(pJson.isMember("draws"))
    {
        if(!validJsonOfField(4, "draws", pJson["draws"], err, true))
            return false;
    }
    if(pJson.isMember("total_matches"))
    {
        if(!validJsonOfField(5, "total_matches", pJson["total_matches"], err, true))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(6, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    return true;
}
bool PlayerStats::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PlayerStats::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("rating"))
    {
        if(!validJsonOfField(1, "rating", pJson["rating"], err, false))
            return false;
    }
    if(pJson.isMember("wins"))
    {
        if(!validJsonOfField(2, "wins", pJson["wins"], err, false))
            return false;
    }
    if(pJson.isMember("losses"))
    {
        if(!validJsonOfField(3, "losses", pJson["losses"], err, false))
            return false;
    }
    if(pJson.isMember("draws"))
    {
        if(!validJsonOfField(4, "draws", pJson["draws"], err, false))
            return false;
    }
    if(pJson.isMember("total_matches"))
    {
        if(!validJsonOfField(5, "total_matches", pJson["total_matches"], err, false))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(6, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    return true;
}
bool PlayerStats::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PlayerStats::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Users PlayerStats::getUsers(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from users where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *userId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Users(r[0]);
}

void PlayerStats::getUsers(const DbClientPtr &clientPtr,
                           const std::function<void(Users)> &rcb,
                           const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from users where id = $1";
    *clientPtr << sql
               << *userId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Users(r[0]));
                    }
               }
               >> ecb;
}
